### ISSUE TITLE
现有问题

### ISSUE THREAD

**Issue by hxgdzyuyi** [mockee/istatic#2]
1 如果在 istatic pull一次之后修改tag 就会没有效果， 而且istatic pull会无情的覆盖修改了的文件。
2 clone 什么的真心慢，有更详细的提示的话就好了

**Comment by mockee** [comment]
1. 本地有一版包含文件比较的还没提交
2. 确实. 今晚加一个

**Comment by mockee** [comment]
@hxgdzyuyi 试试 0.2.5

**Comment by mockee** [comment]
@hxgdzyuyi 
1. fixed
2. 提示信息有所更改

第一次 pull :
![istatic_clone](https://f.cloud.github.com/assets/176544/46570/d655d2a6-5873-11e2-886e-43d2306a8d90.png)
再次 pull:
![istatic_pull](https://f.cloud.github.com/assets/176544/46571/0b1e54a4-5874-11e2-8f1a-023901ae8298.png)

**Comment by hxgdzyuyi** [comment]
Awesome!
